#**SVD**

#import libraries

In [1]:
import numpy as np

#Load the tabular dataset :

dataset :


    [1, 2, 1, 0, 4],

    [2, 3, 4, 0, 2],

    [3, 1, 1, 0, 5],

    [4, 0, 2, 5, 0],

    [5, 4, 0, 1, 2]


In [2]:
dataset = np.array([
    [2, 1, 0, 4],
    [3, 4, 0, 2],
    [1, 1, 0, 5],
    [0, 2, 5, 0],
    [4, 0, 1, 2]
])


#Perform Singular Value Decomposition (SVD)


In [3]:
U, s, VT = np.linalg.svd(dataset)


# Extract the singular values and vectors

In [4]:
singular_values = np.diag(s)
left_singular_vectors = U
right_singular_vectors = VT.T


# Perform dimensionality reduction by selecting top k singular values and vectors


In [7]:
k = 2
reduced_dataset = np.dot(np.dot(left_singular_vectors[:, :k], singular_values[:k, :k]), right_singular_vectors[:, :k].T)


# Print the original and reduced datasets


In [6]:
print("Original Dataset:")
print(dataset)
print("\nReduced Dataset:")
print(reduced_dataset)


Original Dataset:
[[2 1 0 4]
 [3 4 0 2]
 [1 1 0 5]
 [0 2 5 0]
 [4 0 1 2]]

Reduced Dataset:
[[ 2.42783083  1.34469234 -0.28088786  3.55528003]
 [ 2.48095375  2.03039214  1.21169626  3.19513057]
 [ 2.54437376  1.32108273 -0.49569821  3.78477327]
 [ 0.56412157  2.38529993  4.66847769 -0.55714942]
 [ 2.03649155  1.48065473  0.56987114  2.74683942]]


#**Well done :)**